"""Add workspace and user models

Revision ID: 1a9eee0b27ff
Revises: 
Create Date: 2026-03-02 21:31:17.853010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a9eee0b27ff'
down_revision: Union[str, Sequence[str], None] = 'production_baseline_20251228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_service_name'), 'api_keys', ['service_name'], unique=True)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='team_member_role', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='team_member_status', create_constraint=True), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=True)
    op.create_index(op.f('ix_team_members_role'), 'team_members', ['role'], unique=False)
    op.create_index(op.f('ix_team_members_status'), 'team_members', ['status'], unique=False)
    op.create_table('token_revocations',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_revocation_cleanup', 'token_revocations', ['expires_at', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_token_revocations_expires_at'), 'token_revocations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_revocations_jti'), 'token_revocations', ['jti'], unique=False)
    op.create_index(op.f('ix_token_revocations_revoked_at'), 'token_revocations', ['revoked_at'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_provider'), 'user_api_keys', ['provider'], unique=False)
    op.create_index(op.f('ix_user_api_keys_workspace_id'), 'user_api_keys', ['workspace_id'], unique=False)
    op.create_index('uq_user_api_keys_workspace_provider', 'user_api_keys', ['workspace_id', 'provider'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zerodb_project_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=True)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index(op.f('ix_workspaces_zerodb_project_id'), 'workspaces', ['zerodb_project_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('agent_swarm_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('provisioning', 'running', 'paused', 'stopped', 'failed', name='agent_swarm_status', create_constraint=True), nullable=False),
    sa.Column('openclaw_session_key', sa.String(length=255), nullable=True),
    sa.Column('openclaw_agent_id', sa.String(length=255), nullable=True),
    sa.Column('heartbeat_enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_interval', sa.Enum('5m', '15m', '30m', '1h', '2h', name='heartbeat_interval', create_constraint=True), nullable=True),
    sa.Column('heartbeat_checklist', postgresql.ARRAY(String()), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_swarm_instances_name'), 'agent_swarm_instances', ['name'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_openclaw_agent_id'), 'agent_swarm_instances', ['openclaw_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_openclaw_session_key'), 'agent_swarm_instances', ['openclaw_session_key'], unique=True)
    op.create_index(op.f('ix_agent_swarm_instances_status'), 'agent_swarm_instances', ['status'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_user_id'), 'agent_swarm_instances', ['user_id'], unique=False)
    op.create_table('agent_heartbeat_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='heartbeat_execution_status', create_constraint=True), nullable=False),
    sa.Column('checklist_items', postgresql.ARRAY(String()), nullable=True),
    sa.Column('checklist_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('workflow_uuid', sa.String(length=255), nullable=True),
    sa.Column('workflow_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_swarm_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_heartbeat_executions_agent_id'), 'agent_heartbeat_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_heartbeat_executions_status'), 'agent_heartbeat_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_heartbeat_executions_workflow_uuid'), 'agent_heartbeat_executions', ['workflow_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_heartbeat_executions_workflow_uuid'), table_name='agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_heartbeat_executions_status'), table_name='agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_heartbeat_executions_agent_id'), table_name='agent_heartbeat_executions')
    op.drop_table('agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_swarm_instances_user_id'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_status'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_openclaw_session_key'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_openclaw_agent_id'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_name'), table_name='agent_swarm_instances')
    op.drop_table('agent_swarm_instances')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_workspaces_zerodb_project_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('uq_user_api_keys_workspace_provider', table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_workspace_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_provider'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_token_revocations_revoked_at'), table_name='token_revocations')
    op.drop_index(op.f('ix_token_revocations_jti'), table_name='token_revocations')
    op.drop_index(op.f('ix_token_revocations_expires_at'), table_name='token_revocations')
    op.drop_index('ix_revocation_cleanup', table_name='token_revocations')
    op.drop_table('token_revocations')
    op.drop_index(op.f('ix_team_members_status'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_role'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_api_keys_service_name'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
