"""Add workspace_id to agent_swarm_instances

Revision ID: 3cba02be23a6
Revises: d96afe8e6c07
Create Date: 2026-03-02 22:19:18.095487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cba02be23a6'
down_revision: Union[str, Sequence[str], None] = 'd96afe8e6c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_swarm_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('provisioning', 'running', 'paused', 'stopped', 'failed', name='agent_swarm_status', create_constraint=True), nullable=False),
    sa.Column('openclaw_session_key', sa.String(length=255), nullable=True),
    sa.Column('openclaw_agent_id', sa.String(length=255), nullable=True),
    sa.Column('heartbeat_enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_interval', sa.Enum('5m', '15m', '30m', '1h', '2h', name='heartbeat_interval', create_constraint=True), nullable=True),
    sa.Column('heartbeat_checklist', postgresql.ARRAY(String()), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_swarm_instances_name'), 'agent_swarm_instances', ['name'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_openclaw_agent_id'), 'agent_swarm_instances', ['openclaw_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_openclaw_session_key'), 'agent_swarm_instances', ['openclaw_session_key'], unique=True)
    op.create_index(op.f('ix_agent_swarm_instances_status'), 'agent_swarm_instances', ['status'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_user_id'), 'agent_swarm_instances', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_swarm_instances_workspace_id'), 'agent_swarm_instances', ['workspace_id'], unique=False)
    op.create_table('agent_heartbeat_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='heartbeat_execution_status', create_constraint=True), nullable=False),
    sa.Column('checklist_items', postgresql.ARRAY(String()), nullable=True),
    sa.Column('checklist_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('workflow_uuid', sa.String(length=255), nullable=True),
    sa.Column('workflow_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_swarm_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_heartbeat_executions_agent_id'), 'agent_heartbeat_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_heartbeat_executions_status'), 'agent_heartbeat_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_heartbeat_executions_workflow_uuid'), 'agent_heartbeat_executions', ['workflow_uuid'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('openclaw_session_key', sa.String(length=255), nullable=True),
    sa.Column('zerodb_table_name', sa.String(length=100), nullable=True),
    sa.Column('zerodb_conversation_row_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='conversation_status'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_swarm_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_openclaw_session_key'), 'conversations', ['openclaw_session_key'], unique=True)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('team_members', 'invited_by',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'workspace_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('workspaces', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'workspace_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('user_api_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('team_members', 'invited_by',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('team_members', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_openclaw_session_key'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_agent_heartbeat_executions_workflow_uuid'), table_name='agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_heartbeat_executions_status'), table_name='agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_heartbeat_executions_agent_id'), table_name='agent_heartbeat_executions')
    op.drop_table('agent_heartbeat_executions')
    op.drop_index(op.f('ix_agent_swarm_instances_workspace_id'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_user_id'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_status'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_openclaw_session_key'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_openclaw_agent_id'), table_name='agent_swarm_instances')
    op.drop_index(op.f('ix_agent_swarm_instances_name'), table_name='agent_swarm_instances')
    op.drop_table('agent_swarm_instances')
    # ### end Alembic commands ###
